
services:

  chat_service:
    build:
      context: ./chat/
    environment:
      DB_HOST: "localhost"
      DB_NAME: "postgres"
      DB_PORT: "5432"
      DB_USER: "admin"
      DB_PASSWORD: "admin"
      CHAT_PORT: "7001"
    ports:
      - "7001:7001"

  customer_service:
    build:
      context: ./customer/
    environment:
      DB_HOST: "localhost"
      DB_NAME: "postgres"
      DB_PORT: "5432"
      DB_USER: "admin"
      DB_PASSWORD: "admin"
      CUSTOMER_PORT: "7002"
    ports:
      - "7002:7002"

  feed_service:
    build:
      context: ./feed/
    environment:
      DB_HOST: "localhost"
      DB_NAME: "postgres"
      DB_PORT: "5432"
      DB_USER: "admin"
      DB_PASSWORD: "admin"
      CHAT_PORT: "7003"
      CHAT_CONFIG_FILE: "${CHAT_CONFIG_FILE}"
    ports:
      - "7003:7003"

  news_service:
    build:
      context: ./news/
    environment:
      DB_HOST: "localhost"
      DB_NAME: "postgres"
      DB_PORT: "5432"
      DB_USER: "admin"
      DB_PASSWORD: "admin"
      AUTH_PORT: "7004"
    ports:
      - "7004:7004"

  subscription_service:
    build:
      context: ./subscription/
    environment:
      DB_HOST: "localhost"
      DB_NAME: "postgres"
      DB_PORT: "5432"
      DB_USER: "admin"
      DB_PASSWORD: "admin"
      AUTH_PORT: "7005"
    ports:
      - "7005:7005"

  eureka_service:
    build:
      context: ./eureka/
    environment:
      EUREKA_PORT: "7033"
    ports:
      - "7033:7033"

  gateway_service:
    build:
      context: ./gateway/
    environment:
      DB_HOST: "localhost"
      DB_NAME: "middle"
      DB_PORT: "5432"
      DB_USER: "admin"
      DB_PASSWORD: "admin"
      GATEWAY_PORT: "7555"
      CHAT_HOST: "chat_service:7001"
      CUSTOMER_HOST: "customer_service:7002"
      FEED_HOST: "feed_service:7003"
      NEWS_HOST: "news_service:7004"
      SUBSCRIPTION_HOST: "chat_service:7005"
    ports:
      - "7555:7555"

