version: "3.9"

services:
  core-db:
    image: postgres:16.3-alpine3.19
    container_name: postgres-core
    environment:
      POSTGRES_DB: ${DB_NAME:-chat-core}
      POSTGRES_USER: ${DB_USER:-admin}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-admin}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - core-data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT:-5433}:5433
  chat-core:
    image: 'chat-core:latest'
    build:
      context: .
    container_name: chat-core
    depends_on:
      - core-db
    environment:
      CHAT_DB_HOST: ${DB_HOST:-core-db}
      PORT: ${PORT:-8080}
    ports:
      - ${PORT:-8080}:${PORT:-8080}

volumes:
  core-data:
