services:

  chat-postgres:
    container_name: chat-postgres
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    volumes:
      - ./init_databases.sql:/docker-entrypoint-initdb.d/init_databases.sql

  chat-eureka:
    container_name: chat-eureka
    image: chat-eureka
    ports:
      - "8761:8761"
    build:
      context: chat-eureka
      dockerfile: Dockerfile
    environment:
      EUREKA_CLIENT_USERNAME: eureka_client
      EUREKA_CLIENT_PASSWORD: eureka_password
      PORT: 8761

  chat-config:
    container_name: chat-config
    image: chat-config
    ports:
      - "8888:8888"
    build:
      context: chat-config
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: native
      EUREKA_SERVER_URL: http://eureka_client:eureka_password@chat-eureka:8761/eureka
      PORT: 8888

      USER_NAME: chat-user
      NEWS_NAME: chat-news
      FEED_NAME: chat-feed
      MESSENGER_NAME: chat-chat
      SUB_NAME: chat-subscription

      CUSTOMER_URL: chat-customer
      NEWS_URL: chat-news
      FEED_URL: chat-feed
      MESSENGER_URL: chat-messenger
      SUB_URL: chat-sub

      USER_JDBC_URL: jdbc:postgresql://chat-postgres:5432/users
      USER_DB_USER: username
      USER_DB_PASSWORD: password
      SECRET: aGZiYmtiYWllYmNpZWFpZWJsZWNldWNlY2xhZWNhaWJlbGNhZWN3Q0VCV0VXSUM=
      ACCESS: 1
      REFRESH: 24

      MESSENGER_JDBC_URL: jdbc:postgresql://chat-postgres:5432/messenger
      MESSENGER_DB_USER: username
      MESSENGER_DB_PASSWORD: password

      NEWS_R2DBC_URL: r2dbc:postgresql://chat-postgres:5432/news
      NEWS_JDBC_URL: jdbc:postgresql://chat-postgres:5432/news
      NEWS_DB_USER: username
      NEWS_DB_PASSWORD: password

      FEED_JDBC_URL: jdbc:postgresql://chat-postgres:5432/feed
      FEED_DB_USER: username
      FEED_DB_PASSWORD: password

      SUB_JDBC_URL: jdbc:postgresql://chat-postgres:5432/subscription
      SUB_DB_USER: username
      SUB_DB_PASSWORD: password

    depends_on:
      - chat-eureka

  chat-gateway:
    container_name: chat-gateway
    image: chat-gateway
    ports:
      - "8080:8080"
    build:
      context: chat-gateway
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: cloud
      EUREKA_SERVER_URL: http://eureka_client:eureka_password@chat-eureka:8761/eureka
      API_PREFIX: /api/v2
      PORT: 8080
    depends_on:
      - chat-eureka
      - chat-config

  chat-user:
    container_name: chat-user
    image: chat-user
    ports:
      - "8383:8383"
    build:
      context: chat-user
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: cloud
      EUREKA_SERVER_URL: http://eureka_client:eureka_password@chat-eureka:8761/eureka
      PORT: 8383
    depends_on:
      - chat-postgres
      - chat-eureka
      - chat-config
      - chat-gateway

  chat-feed:
    container_name: chat-feed
    image: chat-feed
    ports:
      - "8381:8381"
    build:
      context: chat-feed
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: cloud
      EUREKA_SERVER_URL: http://eureka_client:eureka_password@chat-eureka:8761/eureka
      PORT: 8381
    depends_on:
      - chat-postgres
      - chat-eureka
      - chat-config
      - chat-gateway

  chat-news:
    container_name: chat-news
    image: chat-news
    ports:
      - "8387:8387"
    build:
      context: chat-news
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: cloud
      EUREKA_SERVER_URL: http://eureka_client:eureka_password@chat-eureka:8761/eureka
      PORT: 8387
    depends_on:
      - chat-postgres
      - chat-eureka
      - chat-config
      - chat-gateway


  chat-messenger:
    container_name: chat-messenger
    image: chat-messenger
    ports:
      - "8382:8382"
    build:
      context: chat-messenger
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: cloud
      EUREKA_SERVER_URL: http://eureka_client:eureka_password@chat-eureka:8761/eureka
      PORT: 8382
    depends_on:
      - chat-postgres
      - chat-eureka
      - chat-config
      - chat-gateway


  chat-subscription:
    container_name: chat-subscription
    image: chat-subscription
    ports:
      - "8084:8084"
    build:
      context: chat-subscription
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: cloud
      EUREKA_SERVER_URL: http://eureka_client:eureka_password@chat-eureka:8761/eureka
      API_PREFIX: /api/v2
      PORT: 8084
    depends_on:
      - chat-eureka
      - chat-config