spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/users
    username: username
    password: password


  liquibase:
    enabled: true
    url: jdbc:postgresql://localhost:5432/users
    user: username
    password: password

  security:
    jwt:
      secret: ${SECRET:aGZiYmtiYWllYmNpZWFpZWJsZWNldWNlY2xhZWNhaWJlbGNhZWN3Q0VCV0VXSUM=}
      access: ${ACCESS:1}
      refresh: ${REFRESH:24}

  cloud:
    config:
      enabled: false

eureka:
  client:
    enabled: false

management:
  endpoints:
    web.exposure.include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.boot.context.properties: DEBUG