spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  datasource:
    url: ${USER_JDBC_URL:jdbc:postgresql://localhost:5432/users}
    username: ${USER_DB_USER:username}
    password: ${USER_DB_PASSWORD:password}

  liquibase:
    url: ${USER_JDBC_URL:jdbc:postgresql://postgres:5432/users}
    user: ${USER_DB_USER:username}
    password: ${USER_DB_PASSWORD:password}

  security:
    jwt:
      secret: ${SECRET:aGZiYmtiYWllYmNpZWFpZWJsZWNldWNlY2xhZWNhaWJlbGNhZWN3Q0VCV0VXSUM=}
      access: ${ACCESS:1}
      refresh: ${REFRESH:24}

  cloud:
    config:
      enabled: false
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: basic
      user:
        name: ${USER_NAME:user}
        url: ${USER_URL:user}

eureka:
  client:
    enabled: false

management:
  endpoints:
    web.exposure.include: "*"
  endpoint:
    health:
      show-details: always