spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  r2dbc:
    url: r2dbc:postgresql://${POSTGRES_HOST:chat-postgres}:${POSTGRES_PORT:5432}/${POSTGRES_DB:users}
    username: ${POSTGRES_USER:username}
    password: ${POSTGRES_PASSWORD:password}
    properties:
      schema: application

  liquibase:
    enabled: true
    url: ${USER:jdbc:postgresql://chat-postgres:5432/users}
    user: ${USER_DB_USER:username}
    password: ${USER_DB_PASSWORD:password}
    liquibaseSchema: migration
    change-log: classpath:/db/changelog/master.yml

  security:
    jwt:
      secret: ${SECRET:aGZiYmtiYWllYmNpZWFpZWJsZWNldWNlY2xhZWNhaWJlbGNhZWN3Q0VCV0VXSUM=}
      access: ${ACCESS:1}
      refresh: ${REFRESH:24}

management:
  endpoints:
    web.exposure.include: "*"
  endpoint:
    health:
      show-details: always