server:
  api:
    prefix: /api
spring:
  services:
    urls:
      user: ${USER_NAME:user}
      news: ${NEWS_NAME:news}
      feed: ${FEED_NAME:feed}
      messenger: ${MESSENGER_NAME:messenger}
      subscription: ${SUB_NAME:subscription}
resilience4j:
  circuitbreaker:
    instances:
      sports-user-circuit-breaker:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 2s
        automaticTransitionFromOpenToHalfOpenEnabled: true
        permittedNumberOfCallsInHalfOpenState: 5
      sports-order-circuit-breaker:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 2s
        automaticTransitionFromOpenToHalfOpenEnabled: true
        permittedNumberOfCallsInHalfOpenState: 5
      sports-fight-circuit-breaker:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 2s
        automaticTransitionFromOpenToHalfOpenEnabled: true
        permittedNumberOfCallsInHalfOpenState: 5

management:
  endpoints:
    web.exposure.include: "*"
  endpoint:
    health:
      show-details: always