spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:chat-postgres}:${POSTGRES_PORT:5432}/${POSTGRES_DB:chat}
    username: ${MESSENGER_DB_USER:username}
    password: ${MESSENGER_DB_PASSWORD:password}

  liquibase:
    enabled: true
    url: ${MESSENGER:jdbc:postgresql://chat-postgres:5432/chat}
    username: ${MESSENGER_DB_USER:username}
    password: ${MESSENGER_DB_PASSWORD:password}

  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: basic
      feed:
        name: ${CHAT_NAME:chat}
        url: ${CHAT_URL:chat}

management:
  endpoints:
    web.exposure.include: "*"
  endpoint:
    health:
      show-details: always

#api:
#  job:
#    scheduler:
#      process-debt: "0 * * * * *"
#0 0 0 ? * MON#1