spring:

  r2dbc:
    url: ${CUSTOMER_R2DBC_URL:r2dbc:postgresql://postgres:5432/customer}
    username: ${CUSTOMER_DB_USER:username}
    password: ${CUSTOMER_DB_PASSWORD:password}

  liquibase:
    url: ${CUSTOMER_JDBC_URL:jdbc:postgresql://postgres:5432/customer}
    user: ${CUSTOMER_DB_USER:username}
    password: ${CUSTOMER_DB_PASSWORD:password}

  security:
    jwt:
      secret: ${SECRET:aGZiYmtiYWllYmNpZWFpZWJsZWNldWNlY2xhZWNhaWJlbGNhZWN3Q0VCV0VXSUM=}
      access: ${ACCESS:1}
      refresh: ${REFRESH:24}

management:
  endpoints:
    web.exposure.include: "*"
  endpoint:
    health:
      show-details: always