spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  datasource:
    url: ${CUSTOMER_JDBC_URL:jdbc:postgresql://postgres:5432/customer}
    username: ${CUSTOMER_DB_USER:username}
    password: ${CUSTOMER_DB_PASSWORD:password}

  liquibase:
    url: ${CUSTOMER_JDBC_URL:jdbc:postgresql://postgres:5432/customer}
    user: ${CUSTOMER_DB_USER:username}
    password: ${CUSTOMER_DB_PASSWORD:password}

  security:
    jwt:
      secret: ${SECRET:aGZiYmtiYWllYmNpZWFpZWJsZWNldWNlY2xhZWNhaWJlbGNhZWN3Q0VCV0VXSUM=}
      access: ${ACCESS:1}
      refresh: ${REFRESH:24}

  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: basic
      feed:
        name: ${CUSTOMER_NAME:customer}
        url: ${CUSTOMER_URL:customer}

management:
  endpoints:
    web.exposure.include: "*"
  endpoint:
    health:
      show-details: always