spring:
  config:
    import: "configserver:http://chat-config:8888"
  application:
    name: chat-messenger-cloud
  liquibase:
    username: ${MESSENGER_DB_USER:username}
    password: ${MESSENGER_DB_PASSWORD:password}
    url: jdbc:mysql://${MESSENGER_DB_HOST:localhost}:${MESSENGER_DB_PORT:3306}/${MESSENGER_DB_NAME:yourdb}

eureka:
  client:
    registry-fetch-interval-seconds: 30
    eureka-server-read-timeout-seconds: 10
    eureka-server-connect-timeout-seconds: 60
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://eureka_client:eureka_password@localhost:8761/eureka}