spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  datasource:
    url: ${MESSENGER_JDBC_URL:jdbc:postgresql://localhost:5432/messenger}
    username: ${MESSENGER_DB_USER:username}
    password: ${MESSENGER_DB_PASSWORD:password}

  liquibase:
    url: ${MESSENGER_JDBC_URL:jdbc:postgresql://postgres:5432/chat}
    username: ${MESSENGER_DB_USER:username}
    password: ${MESSENGER_DB_PASSWORD:password}

  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: basic
      chat:
        name: ${MESSENGER_NAME:chat}
        url: ${MESSENGER_URL:chat}

eureka:
  client:
    enabled: false

management:
  endpoints:
    web.exposure.include: "*"
  endpoint:
    health:
      show-details: always