info:
  app:
    name: chat
    description: Chat service
  team:
    name: chat

spring:
  jackson:
    property-naming-strategy: SNAKE_CASE

  application:
    name: chat
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  liquibase:
    liquibaseSchema: migration
    change-log: classpath:/db/changelog/master.yml

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.default_schema: application

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui/index.html


server:
  port: ${PORT:8381}