spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  datasource:
    url: ${SUB_JDBC_URL:jdbc:postgresql://localhost:5432/sub}
    username: ${SUB_DB_USER:username}
    password: ${SUB_DB_PASSWORD:password}

  liquibase:
    url: ${SUB_JDBC_URL:jdbc:postgresql://postgres:5432/sub}
    username: ${SUB_DB_USER:username}
    password: ${SUB_DB_PASSWORD:password}

  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: basic
      feed:
        name: ${SUB_NAME:sub}
        url: ${SUB_URL:sub}

eureka:
  client:
    enabled: false

management:
  endpoints:
    web.exposure.include: "*"
  endpoint:
    health:
      show-details: always