spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  datasource:
    url: ${FEED_JDBC_URL:jdbc:postgresql://localhost:5432/feed}
    username: ${FEED_DB_USER:username}
    password: ${FEED_DB_PASSWORD:password}

  liquibase:
    url: ${FEED_JDBC_URL:jdbc:postgresql://postgres:5432/feed}
    username: ${FEED_DB_USER:username}
    password: ${FEED_DB_PASSWORD:password}

  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: basic
      feed:
        name: ${FEED_NAME:feed}
        url: ${FEED_URL:feed}

eureka:
  client:
    enabled: false

management:
  endpoints:
    web.exposure.include: "*"
  endpoint:
    health:
      show-details: always