spring:
  r2dbc:
    url: ${CUSTOMER_R2DBC_URL:r2dbc:postgresql://postgres:5432/news}
    username: ${CUSTOMER_DB_USER:username}
    password: ${CUSTOMER_DB_PASSWORD:password}

  liquibase:
    url: ${NEWS_JDBC_URL:jdbc:postgresql://postgres:5432/news}
    username: ${NEWS_DB_USER:username}
    password: ${NEWS_DB_PASSWORD:password}

  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: basic
      feed:
        name: ${FEED_NAME:feed}
        url: ${FEED_URL:feed}

eureka:
  client:
    enabled: false

management:
  endpoints:
    web.exposure.include: "*"
  endpoint:
    health:
      show-details: always