info:
  app:
    name: gateway
    description: Gateway service
  team:
    name: chat

spring:
  application:
    name: gateway
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:cloud}

server:
  api:
    prefix: ${API_PREFIX:/api/v2}
  port: ${PORT:8080}